language: groovy
jdk:
- openjdk7
before_script:
- rm -rf build
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Kazuki YAMAMOTO"
  - GIT_EMAIL="yam.kazuki@gmail.com"
  - secure: XsiOtsq2z6bQg7cD2xWcenGtMFtVkI84M1V7JLMwSH0ZV32YYl8LyL7TcieqhEj0/GPEXHgb4duatnxIFomOg1Jku6lP8wO06veLMOpXEZGF5dg+G1+SAqftQzLePsDmEPJW76o4jodWL3pkrTYpnrEn7KUX9olZrXX7lqcunf4=
  - secure: MBJTKTMfBerHYKMeJBrL/R8FwK23BJXALrL477X1letpg2SUj0KN+UKahYqVOGtHRj/C1hbpU84qlovLfuCCbd8CJbtpWw85hnEjnQrDJdHAJs8/ByUhUllT7JxM/1/X/IdGMhxM/k7QulymFlte7HRTDoenHvSXYql5A5ns7YI=
